-- Reconstructed reproducible baseline for WORM ARENA.
-- The original live project briefly used auth.users before migration 20260824152314.
-- For fresh installs we create the effective guest-session schema directly, so the
-- historical guest migration can remain a safe no-op while preserving remote versions.

begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key,
  nickname text not null default 'Игрок' check (char_length(nickname) between 1 and 18),
  best_mass integer not null default 0 check (best_mass >= 0),
  kills integer not null default 0 check (kills >= 0),
  matches integer not null default 0 check (matches >= 0),
  coins integer not null default 0 check (coins >= 0),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.guest_sessions (
  token_hash text primary key check (char_length(token_hash) = 64),
  player_id uuid not null references public.profiles(id) on delete cascade,
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.arena_rooms (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'open' check (status in ('open','closed')),
  host_token uuid,
  host_expires_at timestamptz,
  bus_secret text not null default encode(extensions.gen_random_bytes(32), 'hex'),
  snapshot jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.arena_members (
  room_id uuid not null references public.arena_rooms(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (room_id, player_id)
);

create table if not exists public.arena_tickets (
  ticket uuid primary key,
  room_id uuid not null references public.arena_rooms(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  expires_at timestamptz not null,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.match_results (
  id bigint generated by default as identity primary key,
  room_id uuid references public.arena_rooms(id) on delete set null,
  player_id uuid not null references public.profiles(id) on delete cascade,
  final_mass integer not null check (final_mass >= 0),
  kills integer not null check (kills >= 0),
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists guest_sessions_expiry_idx on public.guest_sessions(expires_at);
create index if not exists guest_sessions_player_idx on public.guest_sessions(player_id, expires_at desc);
create index if not exists arena_members_active_idx on public.arena_members(room_id, last_seen_at desc);
create index if not exists arena_members_player_idx on public.arena_members(player_id, last_seen_at desc);
create index if not exists arena_rooms_open_idx on public.arena_rooms(status, updated_at desc);
create index if not exists arena_tickets_expiry_idx on public.arena_tickets(expires_at);
create index if not exists arena_tickets_player_idx on public.arena_tickets(player_id, created_at desc);
create index if not exists arena_tickets_room_idx on public.arena_tickets(room_id);
create index if not exists match_results_player_idx on public.match_results(player_id, created_at desc);
create index if not exists match_results_room_idx on public.match_results(room_id);

alter table public.profiles enable row level security;
alter table public.guest_sessions enable row level security;
alter table public.arena_rooms enable row level security;
alter table public.arena_members enable row level security;
alter table public.arena_tickets enable row level security;
alter table public.match_results enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.guest_sessions from anon, authenticated;
revoke all on public.arena_rooms from anon, authenticated;
revoke all on public.arena_members from anon, authenticated;
revoke all on public.arena_tickets from anon, authenticated;
revoke all on public.match_results from anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.profiles to service_role;
grant select, insert, update, delete on public.guest_sessions to service_role;
grant select, insert, update, delete on public.arena_rooms to service_role;
grant select, insert, update, delete on public.arena_members to service_role;
grant select, insert, update, delete on public.arena_tickets to service_role;
grant select, insert, update, delete on public.match_results to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.matchmake_arena(p_player_id uuid, p_nickname text, p_max_players integer default 24)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room uuid;
  v_limit integer := greatest(2, least(coalesce(p_max_players, 24), 32));
  v_name text := left(regexp_replace(coalesce(nullif(btrim(p_nickname), ''), 'Игрок'), '[<>[:cntrl:]]', '', 'g'), 18);
begin
  delete from public.arena_members where last_seen_at < now() - interval '25 seconds';
  delete from public.arena_tickets where expires_at < now() or (last_used_at is not null and last_used_at < now() - interval '10 minutes');
  delete from public.guest_sessions where expires_at < now();

  insert into public.profiles(id, nickname, last_seen_at)
  values(p_player_id, v_name, now())
  on conflict(id) do update set nickname = excluded.nickname, last_seen_at = excluded.last_seen_at;

  select r.id into v_room
  from public.arena_rooms r
  where r.status = 'open'
    and (select count(*) from public.arena_members m where m.room_id = r.id and m.last_seen_at >= now() - interval '25 seconds') < v_limit
  order by r.updated_at desc
  for update skip locked
  limit 1;

  if v_room is null then
    insert into public.arena_rooms default values returning id into v_room;
  end if;

  delete from public.arena_members where player_id = p_player_id and room_id <> v_room;
  insert into public.arena_members(room_id, player_id, last_seen_at)
  values(v_room, p_player_id, now())
  on conflict(room_id, player_id) do update set last_seen_at = excluded.last_seen_at;
  update public.arena_rooms set updated_at = now() where id = v_room;
  return v_room;
end;
$$;

create or replace function public.claim_arena_host(p_room_id uuid, p_host_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_claimed boolean := false;
  v_snapshot jsonb;
  v_secret text;
begin
  update public.arena_rooms
  set host_token = p_host_token,
      host_expires_at = now() + interval '9 seconds',
      updated_at = now()
  where id = p_room_id
    and status = 'open'
    and (host_token is null or host_expires_at is null or host_expires_at < now() or host_token = p_host_token)
  returning true, snapshot, bus_secret into v_claimed, v_snapshot, v_secret;

  return jsonb_build_object(
    'claimed', coalesce(v_claimed, false),
    'snapshot', v_snapshot,
    'busSecret', v_secret
  );
end;
$$;

create or replace function public.arena_host_heartbeat(p_room_id uuid, p_host_token uuid, p_snapshot jsonb)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.arena_rooms
  set host_expires_at = now() + interval '9 seconds', snapshot = p_snapshot, updated_at = now()
  where id = p_room_id and status = 'open' and host_token = p_host_token and host_expires_at >= now() - interval '2 seconds';
  return found;
end;
$$;

create or replace function public.release_arena_host(p_room_id uuid, p_host_token uuid, p_snapshot jsonb)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.arena_rooms
  set host_token = null, host_expires_at = null, snapshot = coalesce(p_snapshot, snapshot), updated_at = now()
  where id = p_room_id and host_token = p_host_token;
$$;

create or replace function public.record_verified_result(p_room_id uuid, p_host_token uuid, p_player_id uuid, p_mass integer, p_kills integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_mass integer := greatest(0, least(coalesce(p_mass, 0), 1600));
  v_kills integer := greatest(0, least(coalesce(p_kills, 0), 200));
begin
  if not exists (
    select 1 from public.arena_rooms
    where id = p_room_id and host_token = p_host_token and host_expires_at >= now() - interval '2 seconds'
  ) then return false; end if;

  if not exists (
    select 1 from public.arena_members where room_id = p_room_id and player_id = p_player_id
  ) then return false; end if;

  insert into public.match_results(room_id, player_id, final_mass, kills, verified)
  values(p_room_id, p_player_id, v_mass, v_kills, true);

  update public.profiles
  set best_mass = greatest(best_mass, v_mass),
      kills = kills + v_kills,
      matches = matches + 1,
      coins = coins + v_kills * 6 + (v_mass / 18),
      last_seen_at = now()
  where id = p_player_id;
  return true;
end;
$$;

revoke all on function public.matchmake_arena(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.claim_arena_host(uuid, uuid) from public, anon, authenticated;
revoke all on function public.arena_host_heartbeat(uuid, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.release_arena_host(uuid, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.record_verified_result(uuid, uuid, uuid, integer, integer) from public, anon, authenticated;

grant execute on function public.matchmake_arena(uuid, text, integer) to service_role;
grant execute on function public.claim_arena_host(uuid, uuid) to service_role;
grant execute on function public.arena_host_heartbeat(uuid, uuid, jsonb) to service_role;
grant execute on function public.release_arena_host(uuid, uuid, jsonb) to service_role;
grant execute on function public.record_verified_result(uuid, uuid, uuid, integer, integer) to service_role;

commit;
